[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.build]
cmds = ["cd frontend && npm install --legacy-peer-deps && npm run build && cd .."]

[start]
cmd = "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1"
